Drinks <- read.csv('https://raw.githubusercontent.com/fivethirtyeight/data/master/alcohol-consumption/drinks.csv', stringsAsFactors = FALSE)
View(Drinks)
summary(Drinks, digits = 2)
sd(Drinks$beer_servings)
hist(Drinks$beer_servings)
mean(Drinks$beer_servings)
class(Drinks$beer_servings)
library(dplyr)
log(Drinks$beer_servings) %>% hist(main = "Beer Servings")
plot(log(Drinks$beer_servings), Drinks$wine_servings)
plot(Drinks$beer_servings, xlab = 'Beer')
boxplot(Drinks$beer_servings)